from typing import Protocol


class AIClient(Protocol):
    def list_models(self) -> list[dict]: ...
    def decide(self, model: str, snapshot: dict, policy: str, schema: dict) -> dict: ...
    def research(self, model: str, snapshot: dict) -> dict: ...
